version: "1"
rules:
  - base: packages/xdg-utils
    upstream: archlinux:packages/xdg-utils
    mergeMethod: merge
    mergeUnstable: false
    assignees:
      - KyleGospo
    reviewers:
      - KyleGospo
    conflictReviewers:
      - KyleGospo
